const express = require("express")
const auth = require("../middleware/authentication")
const router = express.Router()
const userController = require("../controller/userController")
const upload = require('../middleware/upload')

router.get("/me", auth, userController.getUser)
router.post("/logout", auth, userController.logout)
router.post("/edit", auth, upload.single('profile'), userController.updateUser)
router.delete("/delete", auth, userController.deleteUser)
router.post('/login', userController.login)
router.post('/register', userController.register)
router.post('/save/:courseId', auth, userController.savedCourse)
router.get('/course/saved', auth, userController.getSavedVideo)
router.post('/send-request', auth, upload.fields([{ name: 'profile', maxCount: 1 }, { name: 'resume', maxCount: 1 }]), userController.setRequest)
router.put('/change-password', auth, userController.changePass)
router.get('/all-teachers',  userController.getAllTeachers)
router.get('/teacher/:id/courses', userController.getOneTeacherCourses)

module.exports = router